/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef, useState} from "react";
import { useGLTF } from "@react-three/drei";
import {useFrame} from "@react-three/fiber";

export function PlantModel(props) {
    const { nodes, materials } = useGLTF("/data/plant.glb");
    const plantModelRef1 = useRef();
    const plantModelRef2 = useRef();
    const plantModelRef3 = useRef();

    const rotationSpeed = 0.0002;
    const [scrollSpeed, setScrollSpeed] = useState(0);

    useFrame(() => {


        // Rotate the plant model on scroll
        if (plantModelRef1.current) {
            plantModelRef1.current.rotation.y += scrollSpeed * rotationSpeed;
        }

        if (plantModelRef2.current) {
            plantModelRef2.current.rotation.y += scrollSpeed * rotationSpeed;
        }

        if (plantModelRef3.current) {
            plantModelRef3.current.rotation.y += scrollSpeed * rotationSpeed;
        }

        setScrollSpeed((prevScrollSpeed) => prevScrollSpeed * 0.95);

    });

    useEffect(() => {
        const handleScroll = (event) => {
            const delta = event.deltaY;
            setScrollSpeed((prevScrollSpeed) => prevScrollSpeed + delta); // Update the scroll speed based on the scroll delta
        };

        window.addEventListener("wheel", handleScroll);

        return () => {
            window.removeEventListener("wheel", handleScroll);
        };
    }, []);

    return (
        <group {...props} dispose={null} >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Matteuccia_struthiopteris__A001.geometry}
                material={materials.leaf}
                ref={plantModelRef1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Matteuccia_struthiopteris__B001.geometry}
                material={materials.leaf}
                ref={plantModelRef2}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Matteuccia_struthiopteris__C001.geometry}
                material={materials.leaf}
                ref={plantModelRef3}
            />
        </group>
    );
}

useGLTF.preload("/data/plant.glb");
